Fix docker image names & reorder file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -31,60 +31,6 @@ npm-package-publish:
   script:
     - !reference [.npm-package-publish, script]
 
-.docker-hub-config:
-  before_script:
-    - |-
-      # Create ~/.docker/config.json file
-      test -d "$HOME/.docker" || mkdir "$HOME/.docker"
-      chmod 0700 "$HOME/.docker"
-      if [ -z "${DOCKER_HUB_USER}" ] || [ -z "${DOCKER_HUB_TOKEN}" ]; then
-        echo "Missing required DOCKER_HUB_* variable(s)"
-        exit 1
-      fi
-      DOCKER_AUTH="$(echo -n "${CI_REGISTRY_USER}:${CI_JOB_TOKEN}" | base64)"
-      DOCKER_HUB_AUTH="$(echo -n "${DOCKER_HUB_USER}:${DOCKER_HUB_TOKEN}" | base64)"
-      cat > "$HOME/.docker/config.json" << EOF
-      {
-        "auths": {
-          "${CI_REGISTRY}": {
-            "auth": "${DOCKER_AUTH}"
-          },
-          "https://index.docker.io/v1/": {
-            "auth": "${DOCKER_HUB_AUTH}"
-          }
-        }
-      }
-      EOF
-      chmod 0600 "$HOME/.docker/config.json"
-
-docker-build:
-  before_script:
-    - !reference [.docker-hub-config, before_script]
-  rules:
-    - if: '$CI_COMMIT_TAG'
-  script:
-    - echo "PACKAGE_VERSION=$CI_COMMIT_TAG" >> .build-args
-    - !reference [.docker-build, script]
-
-docker-push:
-  stage: docker_push
-  dependencies:
-    - docker-build
-  rules:
-    - if: '$CI_COMMIT_TAG'
-  variables:
-    DOCKER_HUB_IMAGE: "kyso/kyso:$CI_COMMIT_TAG"
-  before_script:
-    - !reference [.docker-hub-config, before_script]
-  script:
-    - |-
-      echo "Pulling image '$DOCKER_IMAGE'"
-      docker pull --quiet "$DOCKER_IMAGE"
-      echo "Tagging it as '$DOCKER_HUB_IMAGE'"
-      docker tag "$DOCKER_IMAGE" "$DOCKER_HUB_IMAGE"
-      echo "Pushing it"
-      docker push "$DOCKER_HUB_IMAGE"
-
 build-binaries:
   stage: build_binaries
   image: ${KYSO_CLI_BUILDER_IMAGE}
@@ -217,6 +163,72 @@ push-to-npm:
         done
         exit 1
       fi
+
+.docker-hub-config:
+  before_script:
+    - |-
+      # Create ~/.docker/config.json file
+      test -d "$HOME/.docker" || mkdir "$HOME/.docker"
+      chmod 0700 "$HOME/.docker"
+      if [ -z "${DOCKER_HUB_USER}" ] || [ -z "${DOCKER_HUB_TOKEN}" ]; then
+        echo "Missing required DOCKER_HUB_* variable(s)"
+        exit 1
+      fi
+      DOCKER_AUTH="$(echo -n "${CI_REGISTRY_USER}:${CI_JOB_TOKEN}" | base64)"
+      DOCKER_HUB_AUTH="$(echo -n "${DOCKER_HUB_USER}:${DOCKER_HUB_TOKEN}" | base64)"
+      cat > "$HOME/.docker/config.json" << EOF
+      {
+        "auths": {
+          "${CI_REGISTRY}": {
+            "auth": "${DOCKER_AUTH}"
+          },
+          "https://index.docker.io/v1/": {
+            "auth": "${DOCKER_HUB_AUTH}"
+          }
+        }
+      }
+      EOF
+      chmod 0600 "$HOME/.docker/config.json"
+
+docker-build:
+  before_script:
+    - !reference [.docker-hub-config, before_script]
+  rules:
+    - if: '$CI_COMMIT_TAG'
+  variables:
+    IMAGE_NAME: "$CI_REGISTRY_IMAGE"
+    IMAGE_TAG: "$CI_COMMIT_TAG"
+    DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
+  script:
+    - echo "PACKAGE_VERSION=$CI_COMMIT_TAG" >> .build-args
+    - !reference [.docker-build, script]
+
+container_scanning:
+  variables:
+    CS_DEFAULT_BRANCH_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
+
+docker-push:
+  stage: docker_push
+  extends: .docker-image-and-service
+  dependencies:
+    - docker-build
+  rules:
+    - if: '$CI_COMMIT_TAG'
+  variables:
+    IMAGE_NAME: "$CI_REGISTRY_IMAGE"
+    IMAGE_TAG: "$CI_COMMIT_TAG"
+    DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
+    DOCKER_HUB_IMAGE: "kyso/kyso:$CI_COMMIT_TAG"
+  before_script:
+    - !reference [.docker-hub-config, before_script]
+  script:
+    - |-
+      echo "Pulling image '$DOCKER_IMAGE'"
+      docker pull --quiet "$DOCKER_IMAGE"
+      echo "Tagging it as '$DOCKER_HUB_IMAGE'"
+      docker tag "$DOCKER_IMAGE" "$DOCKER_HUB_IMAGE"
+      echo "Pushing it"
+      docker push "$DOCKER_HUB_IMAGE"
 
 release_tag:
   dependencies:
