Allow failure on npm-publish

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -119,6 +119,7 @@ build-binaries:
 
 push-to-npm:
   stage: push_to_npm
+  allow_failure: true
   image: registry.kyso.io/kyso-io/kyso-cli:builder-v1.0.5
   rules:
     - if: '$CI_COMMIT_TAG'
@@ -150,13 +151,13 @@ push-to-npm:
       echo "Downloading installer '$PKGS_TGZ'"
       curl -s -O --header "JOB-TOKEN: $CI_JOB_TOKEN" "$TGZ_UPLOAD_URL"
     # Push modules to https://registry.npmjs.org
+    - failed=""
     - |-
       INSTALLER_DIR="$PKG_NAME-$PKG_VERS"
       tar xvzf "$PKGS_TGZ" "$INSTALLER_DIR"
       cd "$INSTALLER_DIR"
       # Remove cli package (we have installed it with npm)
       rm -f "kyso-cli-$PKG_VERS.tgz"
-      failed=""
       for tgz in $(ls -tr *.tgz); do
         echo "Adding '$tgz' file to cache"
         npm cache add "$tgz"
@@ -165,19 +166,23 @@ push-to-npm:
       done
       cd ..
       rm -rf "$PKGS_TGZ" "$INSTALLER_DIR"
-      for tgz in $failed; do
-        echo "Publication of the '$tgz' package failed!"
-        echo "Check if it was already published or something else is wrong"
-      done
     # Run npm publish
     - |-
       echo "Publishing package to registry.npmjs.org using npm publish"
       cp -a package.json package.json.orig
       sed -i -e 's%"name": "@kyso-io/kyso-cli"%"name": "kyso"%' package.json
       npm install
-      npm publish --access public || true
+      npm publish --access public || failed="$failed kyso"
       mv package.json.orig package.json
     - if [ -e ".npmrc.orig" ]; then rm ".npmrc"; mv ".npmrc.orig" ".npmrc"; fi
+    - |-
+      if [ "$failed" ]; then
+        for pkg in $failed; do
+          echo "Publication of the '$pkg' package failed!"
+          echo "Check if it was already published or something else is wrong"
+        done
+        exit 1
+      fi
 
 release_tag:
   rules:
